import type { Difficulty, Direction, Level } from "./types";

function addRaisedIslands(grid: string[]): string[] {
  const paintPositions: Array<{ row: number; col: number }> = [];
  grid.forEach((line, row) => {
    [...line].forEach((cell, col) => {
      if (cell === "." || cell === "S") paintPositions.push({ row, col });
    });
  });

  const minRow = Math.min(...paintPositions.map((position) => position.row));
  const maxRow = Math.max(...paintPositions.map((position) => position.row));
  const minCol = Math.min(...paintPositions.map((position) => position.col));
  const maxCol = Math.max(...paintPositions.map((position) => position.col));

  return grid.map((line, row) =>
    [...line]
      .map((cell, col) => {
        if (cell !== " ") return cell;
        const insidePaintBounds = row >= minRow && row <= maxRow && col >= minCol && col <= maxCol;
        return insidePaintBounds ? "#" : " ";
      })
      .join(""),
  );
}

function makeLevel(
  id: number,
  name: string,
  difficulty: Difficulty,
  grid: string[],
  parMoves: number,
  hintLimit: number,
  solution: Direction[],
): Level {
  return { id, name, difficulty, grid: addRaisedIslands(grid), parMoves, hintLimit, solution };
}

export const levels: Level[] = [
  makeLevel(1, "Courtyard Loop", "Easy", [
    "          ",
    " ......   ",
    " .  ...   ",
    " .        ",
    " .        ",
    " .        ",
    " S.....   ",
    " ......   ",
    "          ",
  ], 8, 4, ["DOWN", "RIGHT", "UP", "LEFT", "UP", "RIGHT", "DOWN", "LEFT"]),
  makeLevel(2, "Rail Drop", "Easy", [
    "           ",
    " ......... ",
    " S .       ",
    " . .       ",
    " . .       ",
    " . .       ",
    " . .       ",
    " . .....   ",
    " ......    ",
    "           ",
  ], 9, 4, ["DOWN", "RIGHT", "UP", "RIGHT", "LEFT", "UP", "RIGHT", "LEFT", "RIGHT"]),
  makeLevel(3, "Switch Yard", "Easy", [
    "            ",
    " .......... ",
    "   S..... . ",
    " .......... ",
    " .......... ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
  ], 10, 4, ["RIGHT", "LEFT", "UP", "RIGHT", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT"]),
  makeLevel(4, "Upper Turn", "Easy", [
    "            ",
    " .........S ",
    " . .        ",
    " .........  ",
    " . ..    .  ",
    " . .......  ",
    " .  .       ",
    " .  .       ",
    " .  ..      ",
    " .....      ",
    "            ",
  ], 11, 4, ["LEFT", "DOWN", "RIGHT", "UP", "LEFT", "UP", "LEFT", "RIGHT", "DOWN", "LEFT", "UP"]),
  makeLevel(5, "Twin Shelf", "Easy", [
    "             ",
    "     ....... ",
    "      .    . ",
    " .......S... ",
    " .    . .  . ",
    " .   ....... ",
    " .   .. .    ",
    " .    . .    ",
    " .    . .    ",
    " .    . .    ",
    " ......      ",
    "             ",
  ], 12, 4, ["DOWN", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "UP", "LEFT", "RIGHT", "DOWN", "LEFT", "DOWN"]),
  makeLevel(6, "Long Fork", "Medium", [
    "              ",
    "       .....  ",
    "           .  ",
    " ........  .  ",
    " S..       .  ",
    " . .       .  ",
    " . .       .  ",
    " . .....   .  ",
    " . .   .   .  ",
    " . .   .   .  ",
    " ...........  ",
    "   .....      ",
    "              ",
  ], 14, 5, ["RIGHT", "DOWN", "UP", "DOWN", "RIGHT", "UP", "LEFT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "UP", "LEFT"]),
  makeLevel(7, "First Labyrinth", "Medium", [
    "                ",
    "                ",
    " .........      ",
    " .   .........  ",
    " .............  ",
    "     .   .   .  ",
    "     ....... .  ",
    "     ..  .   .  ",
    "     ..  .   .  ",
    "         .      ",
    "         ....   ",
    "     S......... ",
    "          ..... ",
    "                ",
  ], 18, 5, ["RIGHT", "DOWN", "LEFT", "UP", "LEFT", "RIGHT", "LEFT", "UP", "LEFT", "DOWN", "RIGHT", "DOWN", "UP", "LEFT", "DOWN", "RIGHT", "UP", "RIGHT"]),
  makeLevel(8, "Many Stops", "Medium", [
    "                ",
    "  ..         .  ",
    "  ..   .......  ",
    "   .   . .   .  ",
    " ....... .   .  ",
    " . . . . .   .  ",
    " . . . . .   .  ",
    " . . .........  ",
    " . . .   .   .  ",
    " . . .   .   .  ",
    " ... .   S   .  ",
    "     .........  ",
    "                ",
    "                ",
  ], 18, 5, ["UP", "LEFT", "RIGHT", "LEFT", "DOWN", "LEFT", "RIGHT", "UP", "DOWN", "LEFT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "UP", "LEFT", "DOWN"]),
  makeLevel(9, "Offset Maze", "Medium", [
    "                 ",
    " .....  ......   ",
    " . ......   .    ",
    " . . . ..   .    ",
    " . . . ..   .    ",
    " . . . ..   .    ",
    " . . . ......... ",
    " . . . ..   . .  ",
    " . . . ..   . .  ",
    " . . . ..   . .  ",
    " ............ .  ",
    "     . .      .  ",
    "       .      .  ",
    "       .      S  ",
    "                 ",
  ], 20, 5, ["UP", "LEFT", "RIGHT", "LEFT", "DOWN", "UP", "LEFT", "UP", "DOWN", "RIGHT", "UP", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "LEFT", "UP", "RIGHT", "DOWN"]),
  makeLevel(10, "Split Circuit", "Medium", [
    "                 ",
    "    ............ ",
    " ............... ",
    " .  .      .   . ",
    " .  .      .   . ",
    " ...........   . ",
    " .. .      ..... ",
    " .. .      .     ",
    " .. .      .     ",
    " ......S....     ",
    "  . .            ",
    "  . .            ",
    "  .............  ",
    "                 ",
    "                 ",
  ], 21, 5, ["RIGHT", "LEFT", "UP", "RIGHT", "DOWN", "LEFT", "UP", "DOWN", "UP", "LEFT", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT", "UP", "RIGHT", "LEFT", "RIGHT", "LEFT", "DOWN"]),
  makeLevel(11, "Crosshatch", "Hard", [
    "                  ",
    "    .             ",
    "    ..........    ",
    "    .  .  .  .    ",
    "    .  .  .  .    ",
    "  .........  .    ",
    "  . .  .  .  .    ",
    "  . .  .  .  .    ",
    "  . .  .  .  .    ",
    "  . ..........S.. ",
    "  .    .  .  .  . ",
    "  ............... ",
    "  .    .     .  . ",
    "  .    .......... ",
    "  ............    ",
    "                  ",
  ], 22, 6, ["LEFT", "UP", "DOWN", "RIGHT", "DOWN", "LEFT", "UP", "DOWN", "UP", "DOWN", "UP", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT", "UP", "DOWN", "RIGHT", "LEFT", "RIGHT"]),
  makeLevel(12, "Deep Comb", "Hard", [
    "                  ",
    "  ........ ....   ",
    "        .......   ",
    "        .  .....  ",
    "        .  .  ..  ",
    "        .  .  ..  ",
    "        .  .  ..  ",
    "        .  .  ..  ",
    "   .............  ",
    "   .    .      .  ",
    "  ..............  ",
    " ..............   ",
    "        .         ",
    "        .         ",
    "        ........S ",
    "                  ",
  ], 23, 6, ["LEFT", "UP", "LEFT", "RIGHT", "DOWN", "RIGHT", "UP", "LEFT", "DOWN", "RIGHT", "DOWN", "UP", "LEFT", "UP", "RIGHT", "DOWN", "LEFT", "DOWN", "LEFT", "RIGHT", "UP", "LEFT", "RIGHT"]),
  makeLevel(13, "Twin Courts", "Hard", [
    "                   ",
    "       ..........  ",
    " ........       .  ",
    "      ...       .  ",
    "      ...       .  ",
    "  ...............  ",
    " ............S.... ",
    "  ..  ............ ",
    "  ..    .       .. ",
    "  ..............   ",
    "   .    .          ",
    "   .    .          ",
    "   .    .          ",
    "   .    .          ",
    "   ......          ",
    "                   ",
    "                   ",
  ], 24, 6, ["LEFT", "RIGHT", "DOWN", "LEFT", "UP", "LEFT", "DOWN", "RIGHT", "LEFT", "UP", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT", "LEFT", "RIGHT", "LEFT", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT"]),
  makeLevel(14, "Long Galleries", "Hard", [
    "                   ",
    "                   ",
    " ................. ",
    "     .             ",
    "     .    .......  ",
    "  ....  .........  ",
    "  . ..  . .        ",
    "  . ..  . .        ",
    "  ....S........    ",
    "  . ..... .   .    ",
    "  . .   . .   .    ",
    "  . .   . .   .    ",
    "  . ........  .    ",
    "  .     .     .    ",
    "  .............    ",
    "                   ",
    "                   ",
  ], 25, 6, ["LEFT", "RIGHT", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT", "UP", "DOWN", "RIGHT", "DOWN", "UP", "RIGHT", "UP", "LEFT", "DOWN", "RIGHT", "LEFT", "UP", "RIGHT", "DOWN", "UP", "RIGHT", "LEFT"]),
  makeLevel(15, "Island Circuit", "Hard", [
    "                    ",
    " .................  ",
    " .....     .        ",
    "  ................. ",
    "     .   .S.  .   . ",
    "     .   . .  ... . ",
    "     ..  . .    . . ",
    "      .  . .    . . ",
    "      .  . .    . . ",
    "      .  . .    . . ",
    "      .  . .    . . ",
    " ................ . ",
    "  .  ..... .      . ",
    "  .....    ........ ",
    "           .        ",
    "                    ",
    "                    ",
    "                    ",
  ], 26, 6, ["LEFT", "DOWN", "LEFT", "UP", "RIGHT", "UP", "LEFT", "UP", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "DOWN", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "DOWN", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT", "LEFT"]),
  makeLevel(16, "Deep Channel", "Extra Hard", [
    "                    ",
    "                    ",
    "  ......... ....... ",
    "  .       . .       ",
    " ...      . .       ",
    " .......... .       ",
    "  ...........       ",
    "  . .  ............ ",
    "  . .  .  .  .      ",
    "  . .  .  .  .      ",
    "  . .  .  .  .      ",
    "  . .  .  .  .      ",
    "  S ..........      ",
    "       .   ........ ",
    "    ............... ",
    "                    ",
    "                    ",
    "                    ",
  ], 27, 7, ["UP", "RIGHT", "DOWN", "RIGHT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT", "RIGHT", "UP", "LEFT", "UP", "LEFT", "UP", "RIGHT", "LEFT", "UP", "RIGHT", "DOWN", "RIGHT", "LEFT", "RIGHT", "UP", "RIGHT", "LEFT"]),
  makeLevel(17, "Island Trace", "Extra Hard", [
    "                     ",
    " ..............      ",
    " .          .        ",
    " .          .        ",
    " .   .............   ",
    " .   .      .    .   ",
    " .   ........    .   ",
    " .   . .......   .   ",
    " .   . .    ..   .   ",
    " .   . ...  ..   .   ",
    " .............   .   ",
    "     . . .  .    .   ",
    "     . . .  S    .   ",
    "     ........    .   ",
    "     .   .       .   ",
    "     .   .       .   ",
    "     .   ..........  ",
    "                     ",
  ], 28, 7, ["DOWN", "LEFT", "RIGHT", "UP", "LEFT", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT", "RIGHT", "UP", "LEFT", "UP", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "DOWN", "RIGHT", "LEFT", "UP", "LEFT", "DOWN", "UP", "LEFT", "RIGHT"]),
  makeLevel(18, "Paintworks", "Extra Hard", [
    "                     ",
    "   ............      ",
    "   .    .            ",
    "   .    .            ",
    "   .  ...            ",
    "   .  S       ...    ",
    "   .  .       . .    ",
    "   .  .   .......    ",
    "   .  .   .   .      ",
    " ..............      ",
    "   . .. .........    ",
    "   . .. .     .      ",
    "   . .. .     .      ",
    "   . ..........      ",
    "   . ..       .      ",
    "   . ..       .      ",
    " ..............      ",
    " ...........         ",
    "                     ",
  ], 29, 7, ["UP", "DOWN", "UP", "RIGHT", "UP", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT", "RIGHT", "LEFT", "UP", "RIGHT", "UP", "RIGHT", "DOWN", "LEFT", "DOWN", "RIGHT", "LEFT", "DOWN", "RIGHT", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "RIGHT"]),
  makeLevel(19, "Glass Maze", "Extra Hard", [
    "                      ",
    "         ..........   ",
    "         .        .   ",
    "      ...S        .   ",
    " ..............   .   ",
    "    .         .   .   ",
    "    ................  ",
    "    .         .   ..  ",
    "   .................. ",
    "   ..         .   ... ",
    "   .      ........... ",
    "   .................  ",
    "            ......... ",
    "              .     . ",
    "              .     . ",
    "            ......... ",
    "                      ",
    "                      ",
    "                      ",
  ], 30, 7, ["LEFT", "RIGHT", "DOWN", "UP", "RIGHT", "DOWN", "LEFT", "UP", "RIGHT", "LEFT", "RIGHT", "UP", "LEFT", "DOWN", "RIGHT", "DOWN", "UP", "DOWN", "UP", "LEFT", "DOWN", "UP", "LEFT", "RIGHT", "DOWN", "RIGHT", "LEFT", "RIGHT", "UP", "LEFT"]),
  makeLevel(20, "Crown Labyrinth", "Extra Hard", [
    "                      ",
    "     ...              ",
    "     . .    .         ",
    "     . .    .         ",
    "     . .    .....     ",
    "  ...............     ",
    "  ................... ",
    "  .    .  ........  . ",
    "  .    .         .  . ",
    "  .  .............. . ",
    "  .    . .       .. . ",
    "  .    . .       .. . ",
    "  .    .............. ",
    "  .    . S       ..   ",
    "  .........      ..   ",
    "  .    .  .      ..   ",
    "  .    ............   ",
    "       ....      .    ",
    "                      ",
    "                      ",
  ], 31, 7, ["UP", "LEFT", "RIGHT", "DOWN", "LEFT", "UP", "LEFT", "DOWN", "LEFT", "RIGHT", "DOWN", "UP", "DOWN", "LEFT", "DOWN", "RIGHT", "UP", "LEFT", "DOWN", "UP", "RIGHT", "LEFT", "RIGHT", "DOWN", "UP", "LEFT", "UP", "DOWN", "LEFT", "RIGHT", "DOWN"]),
];
